[theme]
base="dark"
primaryColor="#FFFFFF"
backgroundColor="#000000"
secondaryBackgroundColor="#1a1a1a"
textColor="#FFFFFF"
font="monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

